=== tutopasini/CampeonatoFutebol/campeonato.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="campeonatos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="campeonato" maxOccurs="unbounded"/>
				<xs:element ref="clube" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="posicao" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="diretor" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="clubeDiretor" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="tecnico" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="clubeTecnico" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="torcidaOrganizada" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="clubeTorcidaOrganizada" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="patrocinador" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="clubePatrocinador" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="rodadas" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="jogos" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="classificacaoRodada" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="classificacaoGeral" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		
		<xs:key name="pk_campeonato">
			<xs:selector xpath=".//campeonato"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_jogador">
			<xs:selector xpath="clube/jogador"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_diretor">
			<xs:selector xpath=".//diretor"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_tecnico">
			<xs:selector xpath=".//tecnico"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_torcidaOrganizada">
			<xs:selector xpath=".//torcidaOrganizada"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_posicao">
			<xs:selector xpath=".//posicao"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_clube">
			<xs:selector xpath=".//clube"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_patrocinador">
			<xs:selector xpath=".//patrocinador"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_rodadas">
			<xs:selector xpath=".//rodadas"/>
			<xs:field xpath="@idCampeonato"/>
			<xs:field xpath="@id"/> 
		</xs:key>
		<xs:key name="pk_classificacaoGeral">
			<xs:selector xpath=".//classificacaoGeral"/>
			<xs:field xpath="@idCampeonato"/>
			<xs:field xpath="@colocacao"/>
		</xs:key>
		<xs:key name="pk_classificacaoRodada">
			<xs:selector xpath=".//classificacaoRodada"/>
			<xs:field xpath="@idRodada"/>
			<xs:field xpath="@colocacao"/>
		</xs:key>
		<xs:key name="pk_jogos">
			<xs:selector xpath=".//jogos"/>
			<xs:field xpath="@idRodada"/>
			<xs:field xpath="@idClube1"/>
			<xs:field xpath="@idClube2"/>
		</xs:key>
		<xs:key name="pk_clubeDiretor">
			<xs:selector xpath=".//clubeDiretor"/>
			<xs:field xpath="@idClube"/>
			<xs:field xpath="@idDiretor"/>
		</xs:key>
		<xs:key name="pk_clubeTecnico">
			<xs:selector xpath=".//clubeTecnico"/>
			<xs:field xpath="@idClube"/>
			<xs:field xpath="@idTecnico"/>
		</xs:key>
		<xs:key name="pk_clubeTorcidaOrganizada">
			<xs:selector xpath=".//clubeTorcidaOrganizada"/>
			<xs:field xpath="@idClube"/>
			<xs:field xpath="@idTorcidaOrganizada"/>
		</xs:key>
		<xs:key name="pk_clubePatrocinador">
			<xs:selector xpath=".//clubePatrocinador"/>
			<xs:field xpath="@idClube"/>
			<xs:field xpath="@idPatrocinador"/>
		</xs:key>
		<xs:keyref name="fk_jogador_posicao" refer="pk_posicao">
			<xs:selector xpath="clube/jogador"/>
			<xs:field xpath="idPosicao"/>
		</xs:keyref>
		<xs:keyref name="fk_rodadas_jogador" refer="pk_jogador">
			<xs:selector xpath=".//rodadas"/>
			<xs:field xpath="artilheiro"/>
		</xs:keyref>
		<xs:keyref name="fk_rodadas_campeonato" refer="pk_campeonato">
			<xs:selector xpath=".//rodadas"/>
			<xs:field xpath="@idCampeonato"/>
		</xs:keyref>
		<xs:keyref name="fk_jogos_rodadas" refer="pk_rodadas">
			<xs:selector xpath=".//jogos"/>
			<xs:field xpath="@idCampeonato"/>
			<xs:field xpath="@idRodada"/>
		</xs:keyref>
		<xs:keyref name="fk_jogos_clube1" refer="pk_clube">
			<xs:selector xpath=".//jogos"/>
			<xs:field xpath="@idClube1"/>
		</xs:keyref>
		<xs:keyref name="fk_jogos_clube2" refer="pk_clube">
			<xs:selector xpath=".//jogos"/>
			<xs:field xpath="@idClube2"/>
		</xs:keyref>
		<xs:keyref name="fk_classificaoGeral_campeonato" refer="pk_campeonato">
			<xs:selector xpath=".//classificacaoGeral"/>
			<xs:field xpath="@idCampeonato"/>
		</xs:keyref>
		<xs:keyref name="fk_classificacaoGeral_clube" refer="pk_clube">
			<xs:selector xpath=".//classificacaoGeral"/>
			<xs:field xpath="idClube"/>
		</xs:keyref>
		<xs:keyref name="fk_classificacaoRodada_rodadas" refer="pk_rodadas">
			<xs:selector xpath=".//classificacaoRodada"/>
			<xs:field xpath="@idCampeonato"/>
			<xs:field xpath="@idRodada"/>
		</xs:keyref>
		<xs:keyref name="fk_classificacaoRodada_clube" refer="pk_clube">
			<xs:selector xpath=".//classificacaoRodada"/>
			<xs:field xpath="idClube"/>
		</xs:keyref>
		<xs:keyref name="fk_clubeDiretor_clube" refer="pk_clube">
			<xs:selector xpath=".//clubeDiretor"/>
			<xs:field xpath="@idClube"/>
		</xs:keyref>
		<xs:keyref name="fk_clubeDiretor_diretor" refer="pk_diretor">
			<xs:selector xpath=".//clubeDiretor"/>
			<xs:field xpath="@idDiretor"/>
		</xs:keyref>
		<xs:keyref name="fk_clubeTecnico_clube" refer="pk_clube">
			<xs:selector xpath=".//clubeTecnico"/>
			<xs:field xpath="@idClube"/>
		</xs:keyref>
		<xs:keyref name="fk_clubeTecnico_tecnico" refer="pk_tecnico">
			<xs:selector xpath=".//clubeTecnico"/>
			<xs:field xpath="@idTecnico"/>
		</xs:keyref>
		<xs:keyref name="fk_clubeTorcidaOrganizada_clube" refer="pk_clube">
			<xs:selector xpath=".//clubeTorcidaOrganizada"/>
			<xs:field xpath="@idClube"/>
		</xs:keyref>
		<xs:keyref name="fk_clubeTorcidaOrganizada_torcidaOrganizada" refer="pk_torcidaOrganizada">
			<xs:selector xpath=".//clubeTorcidaOrganizada"/>
			<xs:field xpath="@idTorcidaOrganizada"/>
		</xs:keyref>
		<xs:keyref name="fk_clubePatrocinador_clube" refer="pk_clube">
			<xs:selector xpath=".//clubePatrocinador"/>
			<xs:field xpath="@idClube"/>
		</xs:keyref>
		<xs:keyref name="fk_clubePatrocinador_patrocinador" refer="pk_patrocinador">
			<xs:selector xpath=".//clubePatrocinador"/>
			<xs:field xpath="@idPatrocinador"/>
		</xs:keyref>
	</xs:element>
	
    <xs:element name="jogador">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="nome">
    				<xs:simpleType>
    					<xs:restriction base="xs:string">
    						<xs:minLength value="0"/>
    						<xs:maxLength value="50"/>
    					</xs:restriction>
    				</xs:simpleType>
    			</xs:element>
    			<xs:element name="idPosicao" type="xs:positiveInteger"/>
    		</xs:sequence>
    		<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    	</xs:complexType>
    </xs:element>
    
	<xs:element name="posicao">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="clube">
		<xs:complexType>
    		<xs:sequence>
    			<xs:element name="nome">
    				<xs:simpleType>
    					<xs:restriction base="xs:string">
    						<xs:minLength value="0"/>
    						<xs:maxLength value="50"/>
    					</xs:restriction>
    				</xs:simpleType>
    			</xs:element>
    			<xs:element ref="jogador" maxOccurs="16"/>
    		</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    	</xs:complexType>
	</xs:element>

    <xs:element name="campeonato">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ano" type="xs:positiveInteger"/>
				<xs:element name="nroClubes" type="xs:positiveInteger"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>	
		</xs:complexType>
	</xs:element>

    <xs:element name="diretor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		</xs:complexType>	
	</xs:element>

    <xs:element name="patrocinador">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value ="0"/>
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="torcidaOrganizada">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="tecnico">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nome">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		</xs:complexType>	
	</xs:element>

    <xs:element name="rodadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="artilheiro" type="xs:positiveInteger"/>
				<xs:element name="totalJogos" type="xs:int"/>
				<xs:element name="totalAmarelos" type="xs:int"/>
				<xs:element name="totalVermelhos" type="xs:int"/>
				<xs:element name="totalGols" type="xs:int"/>
			</xs:sequence>
			<xs:attribute name="idCampeonato" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
		</xs:complexType>	
	</xs:element>

    <xs:element name="jogos">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="clube1Gol" type="xs:int"/>
				<xs:element name="clube2Gol" type="xs:int"/>
				<xs:element name="clube1Ponto" type="xs:int"/>
				<xs:element name="clube2Ponto" type="xs:int"/>
				<xs:element name="clube1Amarelo" type="xs:int"/>
				<xs:element name="clube2Amarelo" type="xs:int"/>
				<xs:element name="clube1Vermelho" type="xs:int"/>
				<xs:element name="clube2Vermelho" type="xs:int"/>
			</xs:sequence>
			<xs:attribute name="idCampeonato" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idRodada" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idClube1" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idClube2" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="classificacaoRodada">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="idClube" type="xs:positiveInteger"/>
			</xs:sequence>
			<xs:attribute name="idCampeonato" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idRodada" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="colocacao" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>

    <xs:element name="classificacaoGeral">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="idClube" type="xs:positiveInteger"/>
			</xs:sequence>
			<xs:attribute name="idCampeonato" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="colocacao" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clubeTecnico">
		<xs:complexType>
			<xs:attribute name="idClube" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idTecnico" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clubeTorcidaOrganizada">
		<xs:complexType>
			<xs:attribute name="idClube" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idTorcidaOrganizada" type="xs:positiveInteger" use="required"/>
		</xs:complexType>	
	</xs:element>
	
	<xs:element name="clubeDiretor">
		<xs:complexType>
			<xs:attribute name="idClube" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idDiretor" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="clubePatrocinador">
		<xs:complexType>
			<xs:attribute name="idClube" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="idPatrocinador" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== tutopasini/CampeonatoFutebol/campeonato.xml
<?xml version="1.0" encoding="UTF-8"?>
<campeonatos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/tuto_/git/CampeonatoFutebol/campeonato.xsd">
    <campeonato id="1">
        <nome>Campeonato Brasileiro</nome>
        <ano>2016</ano>
        <nroClubes>20</nroClubes>
    </campeonato>
    
    <clube id="1">
        <nome>Grêmio</nome>
        <jogador id="1">
            <nome>Danrlei</nome>
            <idPosicao>1</idPosicao>
        </jogador>
        <jogador id="2">
            <nome>Jardel</nome>
            <idPosicao>2</idPosicao>
        </jogador>
    </clube>
    <clube id="2">
        <nome>Internacional</nome>
        <jogador id="3">
            <nome>Fernandão</nome>
            <idPosicao>2</idPosicao>
        </jogador>
    </clube>
    <clube id="3">
        <nome>Palmeiras</nome>
        <jogador id="4">
            <nome>Zé Roberto</nome>
            <idPosicao>3</idPosicao>
        </jogador>
    </clube>
    <clube id="4">
        <nome>Santos</nome>
        <jogador id="5">
            <nome>Pelé</nome>
            <idPosicao>2</idPosicao>
        </jogador>
    </clube>
    
    <posicao id="1">
        <nome>Goleiro</nome>
    </posicao>
    <posicao id="2">
        <nome>Atacante</nome>
    </posicao>
    <posicao id="3">
        <nome>Lateral</nome>
    </posicao>
    
    <diretor id="1">
        <nome>Romildo Bolzan</nome>
    </diretor>
    <diretor id="2">
        <nome>Vitorio Piffero</nome>
    </diretor>
    
    <clubeDiretor idClube="1" idDiretor="1"/>
    <clubeDiretor idClube="2" idDiretor="2"/>
    
    <tecnico id="1">
        <nome>Renato Portaluppi</nome>
    </tecnico>
    <tecnico id="2">
        <nome>Celso Roth</nome>
    </tecnico>
    
    <clubeTecnico idClube="2" idTecnico="2"/>
    <clubeTecnico idClube="1" idTecnico="1"/>
    
    <torcidaOrganizada id="1">
        <nome>Geral</nome>
    </torcidaOrganizada>
    <torcidaOrganizada id="2">
        <nome>Guarda Popular</nome>
    </torcidaOrganizada>
    
    <clubeTorcidaOrganizada idClube="1" idTorcidaOrganizada="1"/>
    <clubeTorcidaOrganizada idClube="2" idTorcidaOrganizada="2"/>
    
    <patrocinador id="1">
        <nome>Umbro</nome>
    </patrocinador>
    <patrocinador id="2">
        <nome>Nike</nome>
    </patrocinador>
    <patrocinador id="3">
        <nome>Banrisul</nome>
    </patrocinador>
    
    <clubePatrocinador idClube="1" idPatrocinador="1"/>
    <clubePatrocinador idClube="1" idPatrocinador="3"/>
    <clubePatrocinador idClube="2" idPatrocinador="2"/>
    <clubePatrocinador idClube="2" idPatrocinador="3"/>
    
    <rodadas idCampeonato="1" id="1">
        <artilheiro>2</artilheiro>
        <totalJogos>2</totalJogos>
        <totalAmarelos>9</totalAmarelos>
        <totalVermelhos>1</totalVermelhos>
        <totalGols>6</totalGols>
    </rodadas>
    <rodadas idCampeonato="1" id="2">
        <artilheiro>5</artilheiro>
        <totalJogos>2</totalJogos>
        <totalAmarelos>6</totalAmarelos>
        <totalVermelhos>0</totalVermelhos>
        <totalGols>6</totalGols>
    </rodadas>
    
    
    <jogos idCampeonato="1" idRodada="1" idClube1="1" idClube2="2">
        <clube1Gol>5</clube1Gol>
        <clube2Gol>0</clube2Gol>
        <clube1Ponto>3</clube1Ponto>
        <clube2Ponto>0</clube2Ponto>
        <clube1Amarelo>2</clube1Amarelo>
        <clube2Amarelo>4</clube2Amarelo>
        <clube1Vermelho>0</clube1Vermelho>
        <clube2Vermelho>0</clube2Vermelho>
    </jogos>
    <jogos idCampeonato="1" idRodada="1" idClube1="3" idClube2="4">
        <clube1Gol>1</clube1Gol>
        <clube2Gol>0</clube2Gol>
        <clube1Ponto>3</clube1Ponto>
        <clube2Ponto>0</clube2Ponto>
        <clube1Amarelo>2</clube1Amarelo>
        <clube2Amarelo>1</clube2Amarelo>
        <clube1Vermelho>0</clube1Vermelho>
        <clube2Vermelho>1</clube2Vermelho>
    </jogos>
    <jogos idCampeonato="1" idRodada="2" idClube1="1" idClube2="3">
        <clube1Gol>1</clube1Gol>
        <clube2Gol>0</clube2Gol>
        <clube1Ponto>3</clube1Ponto>
        <clube2Ponto>0</clube2Ponto>
        <clube1Amarelo>1</clube1Amarelo>
        <clube2Amarelo>0</clube2Amarelo>
        <clube1Vermelho>0</clube1Vermelho>
        <clube2Vermelho>0</clube2Vermelho>
    </jogos>
    <jogos idCampeonato="1" idRodada="2" idClube1="2" idClube2="4">
        <clube1Gol>0</clube1Gol>
        <clube2Gol>5</clube2Gol>
        <clube1Ponto>0</clube1Ponto>
        <clube2Ponto>3</clube2Ponto>
        <clube1Amarelo>1</clube1Amarelo>
        <clube2Amarelo>2</clube2Amarelo>
        <clube1Vermelho>0</clube1Vermelho>
        <clube2Vermelho>0</clube2Vermelho>
    </jogos>
    
    <classificacaoRodada idCampeonato="1" idRodada="1" colocacao="1">
        <idClube>1</idClube>
    </classificacaoRodada>
    <classificacaoRodada idCampeonato="1" idRodada="1" colocacao="2">
        <idClube>3</idClube>
    </classificacaoRodada>
    <classificacaoRodada idCampeonato="1" idRodada="1" colocacao="3">
        <idClube>4</idClube>
    </classificacaoRodada>
    <classificacaoRodada idCampeonato="1" idRodada="1" colocacao="4">
        <idClube>2</idClube>
    </classificacaoRodada>
    <classificacaoRodada idCampeonato="1" idRodada="2" colocacao="1">
        <idClube>1</idClube>
    </classificacaoRodada>
    <classificacaoRodada idCampeonato="1" idRodada="2" colocacao="2">
        <idClube>4</idClube>
    </classificacaoRodada>
    <classificacaoRodada idCampeonato="1" idRodada="2" colocacao="3">
        <idClube>3</idClube>
    </classificacaoRodada>
    <classificacaoRodada idCampeonato="1" idRodada="2" colocacao="4">
        <idClube>2</idClube>
    </classificacaoRodada>
    
    <classificacaoGeral idCampeonato="1" colocacao="1">
        <idClube>1</idClube>
    </classificacaoGeral>
    <classificacaoGeral idCampeonato="1" colocacao="2">
        <idClube>4</idClube>
    </classificacaoGeral>
    <classificacaoGeral idCampeonato="1" colocacao="3">
        <idClube>3</idClube>
    </classificacaoGeral>
    <classificacaoGeral idCampeonato="1" colocacao="4">
        <idClube>2</idClube>
    </classificacaoGeral>
    
</campeonatos>
